/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author Ritiele Aldeburg & Anderson
 */
import ModuloA.CacheDMNew;
import ModuloA.Cache_dm_tam_total;
import ModuloB.Cache_ModuloB_Parte1;
import ModuloB.Cache_ModuloB_Parte2;
import ModuloB.Calculo_ModuloB_Parte1;
import ModuloB.Calculo_ModuloB_Parte2;
import ModuloC.CPI_processador;
import ModuloC.Calc_CPI_proc;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

public class NovaTela extends javax.swing.JFrame {

    /**
     * Creates new form NovaTela
     */
    public NovaTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonGravar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonCalcular = new javax.swing.JButton();
        jComboModulos1 = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        Label1 = new javax.swing.JLabel();
        jTextCapacidadeCache = new javax.swing.JTextField();
        /*try{
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("0123456789");

            jTextCapacidadeCache = new javax.swing.JFormattedTextField(telefone);
        }catch(Exception e){
        }*/

        Label2 = new javax.swing.JLabel();
        jTextLarguraPalavra = new javax.swing.JTextField();
        Label3 = new javax.swing.JLabel();
        jTextNumeroPalavra = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextObs = new javax.swing.JTextArea();
        Label14 = new javax.swing.JLabel();
        jTextNumeroVias = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButtonNovo1 = new javax.swing.JButton();
        jButtonGravar1 = new javax.swing.JButton();
        jButtonSair1 = new javax.swing.JButton();
        jButtonCalcular1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        Label4 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();
        Label7 = new javax.swing.JLabel();
        Label8 = new javax.swing.JLabel();
        Label9 = new javax.swing.JLabel();
        Label10 = new javax.swing.JLabel();
        Label11 = new javax.swing.JLabel();
        Label12 = new javax.swing.JLabel();
        Label13 = new javax.swing.JLabel();
        jTextfrequencia = new javax.swing.JTextField();
        /*try{
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("0123456789");

            jTextCapacidadeCache = new javax.swing.JFormattedTextField(telefone);
        }catch(Exception e){
        }*/

        jTextLatenciaPrincipal = new javax.swing.JTextField();
        /*try{
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("0123456789");

            jTextCapacidadeCache = new javax.swing.JFormattedTextField(telefone);
        }catch(Exception e){
        }*/

        jTextLatenciaNivel2 = new javax.swing.JTextField();
        /*try{
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("0123456789");

            jTextCapacidadeCache = new javax.swing.JFormattedTextField(telefone);
        }catch(Exception e){
        }*/

        jTextLatenciaCache = new javax.swing.JTextField();
        /*try{
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("0123456789");

            jTextCapacidadeCache = new javax.swing.JFormattedTextField(telefone);
        }catch(Exception e){
        }*/

        jTextCpiBasico = new javax.swing.JTextField();
        /*try{
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("0123456789");

            jTextCapacidadeCache = new javax.swing.JFormattedTextField(telefone);
        }catch(Exception e){
        }*/

        jTextFalhas1 = new javax.swing.JTextField();
        /*try{
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("0123456789");

            jTextCapacidadeCache = new javax.swing.JFormattedTextField(telefone);
        }catch(Exception e){
        }*/

        jTextFalhas2 = new javax.swing.JTextField();
        /*try{
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("0123456789");

            jTextCapacidadeCache = new javax.swing.JFormattedTextField(telefone);
        }catch(Exception e){
        }*/

        jTextFalhasInstrucao1 = new javax.swing.JTextField();
        /*try{
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("0123456789");

            jTextCapacidadeCache = new javax.swing.JFormattedTextField(telefone);
        }catch(Exception e){
        }*/

        jTextFalhasInstrucao2 = new javax.swing.JTextField();
        /*try{
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("0123456789");

            jTextCapacidadeCache = new javax.swing.JFormattedTextField(telefone);
        }catch(Exception e){
        }*/

        jTextPercentual = new javax.swing.JTextField();
        /*try{
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("0123456789");

            jTextCapacidadeCache = new javax.swing.JFormattedTextField(telefone);
        }catch(Exception e){
        }*/

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_p1 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_p2 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txt_p3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("  Arquitetura e Organização de Computadores II  ");
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Calculadora de AOC II  ", 0, 0, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jButtonNovo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add2.png"))); // NOI18N
        jButtonNovo.setText("Novo Calculo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonGravar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save24x24.png"))); // NOI18N
        jButtonGravar.setText("Salvar Calculo");
        jButtonGravar.setEnabled(false);
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jButtonSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel24x24.png"))); // NOI18N
        jButtonSair.setText("Cancelar");
        jButtonSair.setEnabled(false);
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonCalcular.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar24x24.png"))); // NOI18N
        jButtonCalcular.setText("Calcular");
        jButtonCalcular.setEnabled(false);
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jComboModulos1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboModulos1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modulo A", "Modulo B1", "Modulo B2", "Modulo D" }));
        jComboModulos1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboModulos1ItemStateChanged(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jButtonCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jButtonGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jComboModulos1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboModulos1))
                .addGap(5, 5, 5))
        );

        Label1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label1.setText("Capacidade da cache (em KB) para armazenamento de informações do usuario:");

        jTextCapacidadeCache.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCapacidadeCache.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCapacidadeCache.setEnabled(false);
        jTextCapacidadeCache.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCapacidadeCache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCapacidadeCacheActionPerformed(evt);
            }
        });

        Label2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label2.setText("Largura (em bytes) da palavra:");

        jTextLarguraPalavra.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextLarguraPalavra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextLarguraPalavra.setEnabled(false);
        jTextLarguraPalavra.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextLarguraPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLarguraPalavraActionPerformed(evt);
            }
        });

        Label3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label3.setText("Número de palavras por bloco:");

        jTextNumeroPalavra.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextNumeroPalavra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextNumeroPalavra.setText("1");
        jTextNumeroPalavra.setEnabled(false);
        jTextNumeroPalavra.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextNumeroPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumeroPalavraActionPerformed(evt);
            }
        });

        jTextObs.setEditable(false);
        jTextObs.setColumns(1);
        jTextObs.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextObs.setLineWrap(true);
        jTextObs.setRows(1);
        jTextObs.setText("Tamanho Total da cache:\n\nCapacidade  para armazenamento de informações do usuario:\n\nLargura da palavra:\n\nTamanho do campo de deslocamento:\n\nNúmero de conjuntos da cache:\n\nTamanho do campo de índice do endereço:\n\nTamanho do campo TAG do endereço:");
        jTextObs.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextObs.setEnabled(false);
        jScrollPane4.setViewportView(jTextObs);

        Label14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label14.setText("Número de vias da cache:");

        jTextNumeroVias.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextNumeroVias.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextNumeroVias.setText("1");
        jTextNumeroVias.setEnabled(false);
        jTextNumeroVias.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextNumeroVias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumeroViasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCapacidadeCache, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label3, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextLarguraPalavra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextNumeroPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label14, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNumeroVias, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextCapacidadeCache, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextLarguraPalavra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Label14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextNumeroVias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNumeroPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        jTabbedPane1.addTab("  AOC II - Modulos A,B e D ", jPanel2);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Calculadora de AOC II  ", 0, 0, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jButtonNovo1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add2.png"))); // NOI18N
        jButtonNovo1.setText("Novo Calculo");
        jButtonNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovo1ActionPerformed(evt);
            }
        });

        jButtonGravar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonGravar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save24x24.png"))); // NOI18N
        jButtonGravar1.setText("Salvar Calculo");
        jButtonGravar1.setEnabled(false);
        jButtonGravar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravar1ActionPerformed(evt);
            }
        });

        jButtonSair1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel24x24.png"))); // NOI18N
        jButtonSair1.setText("Cancelar");
        jButtonSair1.setEnabled(false);
        jButtonSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSair1ActionPerformed(evt);
            }
        });

        jButtonCalcular1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCalcular1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar24x24.png"))); // NOI18N
        jButtonCalcular1.setText("Calcular");
        jButtonCalcular1.setEnabled(false);
        jButtonCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcular1ActionPerformed(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButtonNovo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jButtonCalcular1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jButtonGravar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jButtonSair1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonGravar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSair1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCalcular1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );

        Label4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label4.setText("Freqüência de operação do processador (em GHz):");

        Label5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label5.setText("Latência para acesso a bloco na memória principal (em ns):");

        Label6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label6.setText("Latência para acesso a cache de dados nível 2 (em ns):");

        Label7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label7.setText("Latência para acesso a cache de instruções nível 2 (em ns):");

        Label8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label8.setText("CPI básico do processador (quando executa sem falhas de cache):");

        Label9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label9.setText("Taxa de falhas na cache nível 1 de dados:");

        Label10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label10.setText("Taxa de falhas na cache nível 1 de instruções:");

        Label11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label11.setText("Taxa de falhas na cache nível 2 de dados:");

        Label12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label12.setText("Taxa de falhas na cache nível 2 de instruções:");

        Label13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label13.setText("Percentual de instruções do tipo Load/Store:");

        jTextfrequencia.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextfrequencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextfrequencia.setEnabled(false);
        jTextfrequencia.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextfrequencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextfrequenciaActionPerformed(evt);
            }
        });

        jTextLatenciaPrincipal.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextLatenciaPrincipal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextLatenciaPrincipal.setEnabled(false);
        jTextLatenciaPrincipal.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextLatenciaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLatenciaPrincipalActionPerformed(evt);
            }
        });

        jTextLatenciaNivel2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextLatenciaNivel2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextLatenciaNivel2.setEnabled(false);
        jTextLatenciaNivel2.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextLatenciaNivel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLatenciaNivel2ActionPerformed(evt);
            }
        });

        jTextLatenciaCache.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextLatenciaCache.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextLatenciaCache.setEnabled(false);
        jTextLatenciaCache.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextLatenciaCache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLatenciaCacheActionPerformed(evt);
            }
        });

        jTextCpiBasico.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCpiBasico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCpiBasico.setEnabled(false);
        jTextCpiBasico.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCpiBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCpiBasicoActionPerformed(evt);
            }
        });

        jTextFalhas1.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextFalhas1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFalhas1.setEnabled(false);
        jTextFalhas1.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextFalhas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFalhas1ActionPerformed(evt);
            }
        });

        jTextFalhas2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextFalhas2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFalhas2.setEnabled(false);
        jTextFalhas2.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextFalhas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFalhas2ActionPerformed(evt);
            }
        });

        jTextFalhasInstrucao1.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextFalhasInstrucao1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFalhasInstrucao1.setEnabled(false);
        jTextFalhasInstrucao1.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextFalhasInstrucao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFalhasInstrucao1ActionPerformed(evt);
            }
        });

        jTextFalhasInstrucao2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextFalhasInstrucao2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFalhasInstrucao2.setEnabled(false);
        jTextFalhasInstrucao2.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextFalhasInstrucao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFalhasInstrucao2ActionPerformed(evt);
            }
        });

        jTextPercentual.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextPercentual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextPercentual.setEnabled(false);
        jTextPercentual.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextPercentual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPercentualActionPerformed(evt);
            }
        });

        jTabbedPane2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        txt_p1.setEditable(false);
        txt_p1.setColumns(1);
        txt_p1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_p1.setLineWrap(true);
        txt_p1.setRows(1);
        txt_p1.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txt_p1.setEnabled(false);
        jScrollPane5.setViewportView(txt_p1);

        jTabbedPane2.addTab("  Entradas  ", jScrollPane5);

        txt_p2.setEditable(false);
        txt_p2.setColumns(1);
        txt_p2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_p2.setLineWrap(true);
        txt_p2.setRows(1);
        txt_p2.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txt_p2.setEnabled(false);
        jScrollPane6.setViewportView(txt_p2);

        jTabbedPane2.addTab("  Calculos com Cache nivel 2  ", jScrollPane6);

        txt_p3.setEditable(false);
        txt_p3.setColumns(1);
        txt_p3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_p3.setLineWrap(true);
        txt_p3.setRows(1);
        txt_p3.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txt_p3.setEnabled(false);
        jScrollPane7.setViewportView(txt_p3);

        jTabbedPane2.addTab("  Calculos sem Cache nivel 2  ", jScrollPane7);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(Label9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFalhas1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(Label11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFalhas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Label12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFalhasInstrucao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFalhasInstrucao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Label4)
                                        .addComponent(Label5)
                                        .addComponent(Label6)
                                        .addComponent(Label7)
                                        .addComponent(Label8))
                                    .addGap(22, 22, 22)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextCpiBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextLatenciaCache, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextLatenciaNivel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextLatenciaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextfrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(Label13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextPercentual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(217, 217, 217))))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextfrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextLatenciaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextLatenciaNivel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextLatenciaCache, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCpiBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFalhas1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFalhasInstrucao1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFalhas2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFalhasInstrucao2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        jTabbedPane1.addTab("  AOC II - Modulo C", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void limpaCampo() {
        jTextObs.setText(null);
        txt_p1.setText(null);
        txt_p2.setText(null);
        txt_p3.setText(null);
        jTextCapacidadeCache.setText("");
        jTextLarguraPalavra.setText("");
        jTextNumeroPalavra.setText("1");
        jTextPercentual.setText("");
        jTextLatenciaPrincipal.setText("");
        jTextLatenciaNivel2.setText("");
        jTextLatenciaCache.setText("");
        jTextCpiBasico.setText("");
        jTextFalhas1.setText("");
        jTextFalhas2.setText("");
        jTextFalhasInstrucao1.setText("");
        jTextFalhasInstrucao2.setText("");
        jTextfrequencia.setText("");

    }


    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        jTabbedPane1.setEnabledAt(1, false);
        if (jComboModulos1.getSelectedIndex() == 0) {
            this.limpaCampo();
            this.jComboModulos1.setEnabled(false);
            this.jTextNumeroPalavra.setEnabled(false);
            this.jTextCapacidadeCache.setEnabled(true);
            this.jTextLarguraPalavra.setEnabled(true);
            this.jButtonNovo.setEnabled(false);
            this.jButtonCalcular.setEnabled(true);
            this.jButtonSair.setEnabled(true);
        } else {
            if ((jComboModulos1.getSelectedIndex() == 1)) {
                this.limpaCampo();
                this.jTextNumeroPalavra.setEnabled(true);
                this.jComboModulos1.setEnabled(false);
                this.jTextNumeroPalavra.setEnabled(true);
                this.jTextCapacidadeCache.setEnabled(true);
                this.jTextLarguraPalavra.setEnabled(true);
                this.jButtonNovo.setEnabled(false);
                this.jButtonCalcular.setEnabled(true);
                this.jButtonSair.setEnabled(true);
            } else {
                if ((jComboModulos1.getSelectedIndex() == 2)) {
                    this.limpaCampo();
                    this.jTextNumeroPalavra.setText("");
                    this.jTextNumeroPalavra.setEnabled(true);
                    this.jComboModulos1.setEnabled(false);
                    this.jTextNumeroPalavra.setEnabled(true);
                    this.jTextCapacidadeCache.setEnabled(true);
                    this.jTextLarguraPalavra.setEnabled(true);
                    this.jButtonNovo.setEnabled(false);
                    this.jButtonCalcular.setEnabled(true);
                    this.jButtonSair.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        File arquivo = new File("Calculo.txt");
        String texto = "";
        String[] txt = null;
        PrintWriter pw = null;
        try {
            pw = new PrintWriter(new File("Calculo.txt"));

            texto = jTextObs.getText();
            txt = texto.split("\n");
            for (int i = 0; i < txt.length; i++) {
                pw.println(txt[i]);
            }
            pw.close();
            JOptionPane.showMessageDialog(null, "Calculo Salvo com Sucesso!!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);

        } catch (FileNotFoundException ex) {
            throw new RuntimeException(ex);
        }
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        jTabbedPane1.setEnabledAt(1, true);
        this.limpaCampo();
        this.jComboModulos1.setSelectedIndex(0);
        jTextNumeroPalavra.setText("1");
        Label1.setText("Capacidade da cache (em KB) para armazenamento de informações do usuario:");
        Label2.setText("Largura (em bytes) da palavra:");
        Label3.setText("Número de palavras por bloco:");
        this.jComboModulos1.setEnabled(true);
        this.jTextNumeroPalavra.setEnabled(false);
        this.jTextCapacidadeCache.setEnabled(false);
        this.jTextLarguraPalavra.setEnabled(false);
        this.jButtonGravar.setEnabled(false);
        this.jButtonNovo.setEnabled(true);
        this.jButtonSair.setEnabled(false);
        this.jButtonCalcular.setEnabled(false);

    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed

        if (jComboModulos1.getSelectedIndex() == 0) {
            if (jTextCapacidadeCache.getText().equals("0") || jTextCapacidadeCache.getText().equals("") || jTextLarguraPalavra.getText().equals("0") || jTextLarguraPalavra.getText().equals("") || jTextNumeroPalavra.getText().equals("0") || jTextNumeroPalavra.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Verifique os Valores de Entrada!!", "Erro ao Calcular", JOptionPane.WARNING_MESSAGE);
            } else {
                //Le dados da tela e coloca na cache
                CacheDMNew cache = new CacheDMNew(Float.parseFloat(jTextCapacidadeCache.getText()), Float.parseFloat(jTextLarguraPalavra.getText()), Float.parseFloat(jTextNumeroPalavra.getText()));
                //inicializa a cache1
                CacheDMNew cache1 = new CacheDMNew(0, 0, 1);
                //Estancia Cache_dm_tam_total
                Cache_dm_tam_total result_calc = new Cache_dm_tam_total();
                //efetua o calculo e salva na cache1
                cache1 = result_calc.Calc(cache);
                //Mostra na tela os resultados
                jTextObs.setText("Tamanho Total da cache: " + cache1.getT_total() + "\n\n"
                        + "Capacidade  para armazenamento de informações do usuario: " + cache1.getT_user() + "\n\n"
                        + "Largura da palavra: " + cache1.getT_word() + "\n\n"
                        + "Numero de Palavras por Bloco" + cache1.getN_word_bloco() + "\n\n"
                        + "Tamanho do campo de deslocamento: " + cache1.getOb() + "\n\n"
                        + "Número de conjuntos da cache: " + cache1.getN_conj() + "\n\n"
                        + "Tamanho do campo de índice do endereço: " + cache1.getT_ind() + "\n\n"
                        + "Tamanho do campo TAG do endereço: " + cache1.getTag() + "\n\n ");

                this.jButtonGravar.setEnabled(true);
            }
        } else {
            if (jComboModulos1.getSelectedIndex() == 1) {
                if (jTextCapacidadeCache.getText().equals("0") || jTextCapacidadeCache.getText().equals("") || jTextLarguraPalavra.getText().equals("0") || jTextLarguraPalavra.getText().equals("") || jTextNumeroPalavra.getText().equals("0") || jTextNumeroPalavra.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Verifique os Valores de Entrada!!", "Erro ao Calcular", JOptionPane.WARNING_MESSAGE);
                } else {
                    //Le dados da tela e coloca na cache
                    Cache_ModuloB_Parte1 cache_b = new Cache_ModuloB_Parte1(Float.parseFloat(jTextCapacidadeCache.getText()), Float.parseFloat(jTextLarguraPalavra.getText()), Float.parseFloat(jTextNumeroPalavra.getText()));
                    //inicializa a cache1
                    Cache_ModuloB_Parte1 cache1_b = new Cache_ModuloB_Parte1(0, 0, 1);
                    //estancia calculo modulo b1
                    Calculo_ModuloB_Parte1 result_calc_b1 = new Calculo_ModuloB_Parte1();
                    //efetua o calculo e salva na cache1
                    cache1_b = result_calc_b1.Calc(cache_b);

                    jTextObs.setText("Tamanho Total da cache: " + cache1_b.getT_total() + "\n\n"
                            + "Capacidade  para armazenamento de informações do usuario: " + cache1_b.getT_user() + "\n\n"
                            + "Largura da palavra: " + cache1_b.getT_word() + "\n\n"
                            + "Numero de Palavras por Bloco" + cache1_b.getN_word_bloco() + "\n\n"
                            + "Tamanho do campo de deslocamento: " + cache1_b.getOb() + "\n\n"
                            + "Tamanho do Endereço: " + cache1_b.getT_end() + "\n\n"
                            + "Offiset de Palavra: " + cache1_b.getOp() + "\n\n"
                            + "Tamanho de Overhad: " + cache1_b.getOverhad() + "\n\n"
                            + "Número de conjuntos da cache: " + cache1_b.getN_conj() + "\n\n"
                            + "Tamanho do campo de índice do endereço: " + cache1_b.getT_ind() + "\n\n"
                            + "Tamanho do campo TAG do endereço: " + cache1_b.getTag() + "\n\n ");
                    jButtonGravar.setEnabled(true);
                }
            } else {
                if (jComboModulos1.getSelectedIndex() == 2) {
                    if (jTextCapacidadeCache.getText().equals("0") || jTextCapacidadeCache.getText().equals("") || jTextLarguraPalavra.getText().equals("0") || jTextLarguraPalavra.getText().equals("") || jTextNumeroPalavra.getText().equals("0") || jTextNumeroPalavra.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Verifique os Valores de Entrada!!", "Erro ao Calcular", JOptionPane.WARNING_MESSAGE);
                    } else {
                        //Le dados da tela e coloca na cache
                        Cache_ModuloB_Parte2 cache_b2 = new Cache_ModuloB_Parte2(Integer.parseInt(jTextCapacidadeCache.getText()), Integer.parseInt(jTextLarguraPalavra.getText()), Float.parseFloat(jTextNumeroPalavra.getText()));
                        //inicializa a cache1
                        Cache_ModuloB_Parte2 cache1_b2 = new Cache_ModuloB_Parte2(0, 0, 1);
                        //estancia calculo modulo b1
                        Calculo_ModuloB_Parte2 result_calc_b2 = new Calculo_ModuloB_Parte2();
                        //efetua o calculo e salva na cache1
                        cache1_b2 = result_calc_b2.Calc(cache_b2);

                        jTextObs.setText("Número de bits do campo de índice do endereço: " + cache1_b2.getT_ind() + "\n\n"
                                + "Largura (em bytes) do endereço: " + cache1_b2.getT_end() + "\n\n"
                                + "Overhead (em bytes) da cache: " + cache1_b2.getOverhad() + "\n\n"
                                + "Numero de conjuntos da cache: " + cache1_b2.getN_conj() + "\n\n"
                                + "Offset de Bloco: " + cache1_b2.getO_bloco() + "\n\n"
                                + "Tamanho do Bloco: " + cache1_b2.getT_bloco() + "\n\n"
                                + "Tamanho do campo TAG do endereço: " + cache1_b2.getTag() + "\n\n ");
                        jButtonGravar.setEnabled(true);
                    }
                } else {

                }
            }
        }

    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jComboModulos1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboModulos1ItemStateChanged
        if (jComboModulos1.getSelectedIndex() == 0 || jComboModulos1.getSelectedIndex() == 1) {
            jTextNumeroPalavra.setText("1");
            Label1.setText("Capacidade da cache (em KB) para armazenamento de informações do usuario:");
            Label2.setText("Largura (em bytes) da palavra:");
            Label3.setText("Número de palavras por bloco:");
        } else {
            if (jComboModulos1.getSelectedIndex() == 2) {
                jTextNumeroPalavra.setText("");
                Label1.setText("Número de bits do campo de índice do endereço:");
                Label2.setText("Largura (em bytes) do endereço:");
                Label3.setText("Overhead (em bytes) da cache:");
            } else {

            }
        }
    }//GEN-LAST:event_jComboModulos1ItemStateChanged

    private void jTextCapacidadeCacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCapacidadeCacheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCapacidadeCacheActionPerformed

    private void jTextLarguraPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLarguraPalavraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLarguraPalavraActionPerformed

    private void jTextNumeroPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumeroPalavraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumeroPalavraActionPerformed

    private void jTextPercentualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPercentualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPercentualActionPerformed

    private void jTextFalhasInstrucao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFalhasInstrucao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFalhasInstrucao2ActionPerformed

    private void jTextFalhasInstrucao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFalhasInstrucao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFalhasInstrucao1ActionPerformed

    private void jTextFalhas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFalhas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFalhas2ActionPerformed

    private void jTextFalhas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFalhas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFalhas1ActionPerformed

    private void jTextCpiBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCpiBasicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCpiBasicoActionPerformed

    private void jTextLatenciaCacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLatenciaCacheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLatenciaCacheActionPerformed

    private void jTextLatenciaNivel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLatenciaNivel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLatenciaNivel2ActionPerformed

    private void jTextLatenciaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLatenciaPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLatenciaPrincipalActionPerformed

    private void jTextfrequenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextfrequenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextfrequenciaActionPerformed

//
    private void jButtonCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcular1ActionPerformed
        //        this.jButtonGravar1.setEnabled(true);
        if (jTextPercentual.getText().equals("") || jTextLatenciaPrincipal.getText().equals("") || jTextLatenciaNivel2.getText().equals("") || jTextLatenciaCache.getText().equals("") || jTextCpiBasico.getText().equals("") || jTextFalhas1.getText().equals("") || jTextFalhas2.getText().equals("") || jTextFalhasInstrucao1.getText().equals("") || jTextFalhasInstrucao2.getText().equals("") || jTextfrequencia.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Verifique os Valores de Entrada!!", "Erro ao Calcular", JOptionPane.WARNING_MESSAGE);
        } else {
            //Le dados da tela e coloca na cache
            CPI_processador cpi = new CPI_processador(
                Float.parseFloat(jTextfrequencia.getText()),
                Float.parseFloat(jTextLatenciaPrincipal.getText()),
                Float.parseFloat(jTextLatenciaNivel2.getText()),
                Float.parseFloat(jTextLatenciaCache.getText()),
                Float.parseFloat(jTextCpiBasico.getText()),
                Float.parseFloat(jTextFalhas1.getText()),
                Float.parseFloat(jTextFalhasInstrucao1.getText()),
                Float.parseFloat(jTextFalhas2.getText()),
                Float.parseFloat(jTextFalhasInstrucao2.getText()),
                Float.parseFloat(jTextPercentual.getText()));
            //Estancia Cache_dm_tam_total
            Calc_CPI_proc result_calc = new Calc_CPI_proc();
            //efetua o calculo e salva na cache1
            cpi = result_calc.calc(cpi);
            //Mostra na tela os resultados
            txt_p1.setText("Frequência de operação do processador : " + cpi.getFreq_proc() + " Ghz\n\n"
                + "Periodo de operação do processador : " + cpi.getT_proc() + " ns\n\n"
                + "Latência para acesso a bloco na memória principal : " + cpi.getLmp_ns() + " ns\n\n"
                + "Latência para acesso a bloco na memória principal : " + cpi.getLmp_ci() + " ciclos\n\n"
                + "Latência para acesso a cache de dados nível 2 : " + cpi.getLcd_n2_ns() + " ns\n\n"
                + "Latência para acesso a cache de dados nível 2 : " + cpi.getLcd_n2_ci() + " ciclos\n\n"
                + "Latência para acesso a cache de instruções nível 2 :" + cpi.getLci_n2_ns() + " ns\n\n"
                + "Latência para acesso a cache de instruções nível 2 :" + cpi.getLci_n2_ci() + " ciclos\n\n"
                + "CPI básico do processador (quando executa sem falhas de cache): " + cpi.getCpi_base() + " ciclos\n\n"
                + "Taxa de falhas na cache nível 1 de dados: " + cpi.getTfcd_n1() + " %\n\n"
                + "Taxa de falhas na cache nível 1 de instruções: " + cpi.getTfci_n1() + " %\n\n"
                + "Taxa de falhas na cache nível 2 de dados: " + cpi.getTfcd_n2() + " %\n\n "
                + "Taxa de falhas na cache nível 2 de instruções: " + cpi.getTfci_n2() + " %\n\n"
                + "Percentual de instruções do tipo Load/Store: " + cpi.getTils() + " %\n\n");

            txt_p2.setText("Calculo de falhas de cache de instruções nivel 1 : " + cpi.getCfci_n1_1() + " ciclos\n\n"
                + "Calculo de falhas de cache de dados nivel 1 : " + cpi.getCfcd_n1_1() + " ciclos\n\n"
                + "Calculo de falhas de cache de intruções nivel 2 : " + cpi.getCfci_n2_1() + " ciclos\n\n"
                + "Calculo de falhas de cache de dados nivel 2 : " + cpi.getCfcd_n2_1() + " ciclos\n\n"
                + "CPI final com a presença cache nivel 2 : " + cpi.getCpif_cn2() + " ciclos");

            txt_p3.setText("Calculo de falhas de cache de instruções nivel : " + cpi.getCfci_n1_2() + " ciclos\n\n"
                + "Calculo de falhas de cache de dados nivel 1 : " + cpi.getCfcd_n1_2() + " ciclos\n\n"
                + "CPI final sem a presença cache nivel 2 : " + cpi.getCpif_sn2() + " ciclos");
            this.jButtonGravar1.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonCalcular1ActionPerformed

    private void jButtonSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSair1ActionPerformed
        jTabbedPane1.setEnabledAt(0, true);
        this.limpaCampo();
        this.jTextPercentual.setEnabled(false);
        this.jTextLatenciaPrincipal.setEnabled(false);
        this.jTextLatenciaNivel2.setEnabled(false);
        this.jTextLatenciaCache.setEnabled(false);
        this.jTextCpiBasico.setEnabled(false);
        this.jTextFalhas1.setEnabled(false);
        this.jTextFalhas2.setEnabled(false);
        this.jTextFalhasInstrucao1.setEnabled(false);
        this.jTextFalhasInstrucao2.setEnabled(false);
        this.jTextfrequencia.setEnabled(false);
        this.jButtonGravar1.setEnabled(false);
        this.jButtonNovo1.setEnabled(true);
        this.jButtonSair1.setEnabled(false);
        this.jButtonCalcular1.setEnabled(false);
    }//GEN-LAST:event_jButtonSair1ActionPerformed

    private void jButtonGravar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravar1ActionPerformed
        File arquivo = new File("Calculo.txt");
        String texto = "";
        String[] txt = null;
        PrintWriter pw = null;
        try {
            pw = new PrintWriter(new File("Calculo.txt"));

            texto = txt_p1.getText()+"\n\n"+txt_p2.getText()+"\n\n"+txt_p3.getText();
            txt = texto.split("\n");
            for (int i = 0; i < txt.length; i++) {
                pw.println(txt[i]);
            }
            pw.close();
            JOptionPane.showMessageDialog(null, "Calculo Salvo com Sucesso!!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);

        } catch (FileNotFoundException ex) {
            throw new RuntimeException(ex);
        }
    }//GEN-LAST:event_jButtonGravar1ActionPerformed

    private void jButtonNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovo1ActionPerformed
        jTabbedPane1.setEnabledAt(0, false);
        this.limpaCampo();
        this.jTextPercentual.setEnabled(true);
        this.jTextLatenciaPrincipal.setEnabled(true);
        this.jTextLatenciaNivel2.setEnabled(true);
        this.jTextLatenciaCache.setEnabled(true);
        this.jTextCpiBasico.setEnabled(true);
        this.jTextFalhas1.setEnabled(true);
        this.jTextFalhas2.setEnabled(true);
        this.jTextFalhasInstrucao1.setEnabled(true);
        this.jTextFalhasInstrucao2.setEnabled(true);
        this.jTextfrequencia.setEnabled(true);
        this.jButtonNovo1.setEnabled(false);
        this.jButtonCalcular1.setEnabled(true);
        this.jButtonSair1.setEnabled(true);
    }//GEN-LAST:event_jButtonNovo1ActionPerformed

    private void jTextNumeroViasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumeroViasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumeroViasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label10;
    private javax.swing.JLabel Label11;
    private javax.swing.JLabel Label12;
    private javax.swing.JLabel Label13;
    private javax.swing.JLabel Label14;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label8;
    private javax.swing.JLabel Label9;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonCalcular1;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonGravar1;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonNovo1;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSair1;
    private javax.swing.JComboBox<String> jComboModulos1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextCapacidadeCache;
    private javax.swing.JTextField jTextCpiBasico;
    private javax.swing.JTextField jTextFalhas1;
    private javax.swing.JTextField jTextFalhas2;
    private javax.swing.JTextField jTextFalhasInstrucao1;
    private javax.swing.JTextField jTextFalhasInstrucao2;
    private javax.swing.JTextField jTextLarguraPalavra;
    private javax.swing.JTextField jTextLatenciaCache;
    private javax.swing.JTextField jTextLatenciaNivel2;
    private javax.swing.JTextField jTextLatenciaPrincipal;
    private javax.swing.JTextField jTextNumeroPalavra;
    private javax.swing.JTextField jTextNumeroVias;
    private javax.swing.JTextArea jTextObs;
    private javax.swing.JTextField jTextPercentual;
    private javax.swing.JTextField jTextfrequencia;
    private javax.swing.JTextArea txt_p1;
    private javax.swing.JTextArea txt_p2;
    private javax.swing.JTextArea txt_p3;
    // End of variables declaration//GEN-END:variables
}
