/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import ModuloA.CacheDMNew;
import ModuloA.Cache_dm_tam_total;
import javax.swing.JOptionPane;

/**
 *
 * @author Ritiele Aldeburg
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonGravar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonCalcular = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextObs = new javax.swing.JTextArea();
        jTextCapacidadeCache = new javax.swing.JTextField();
        /*try{
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("0123456789");

            jTextCapacidadeCache = new javax.swing.JFormattedTextField(telefone);
        }catch(Exception e){
        }*/

        LabelValorCus112 = new javax.swing.JLabel();
        LabelValorCus113 = new javax.swing.JLabel();
        jTextLarguraPalavra = new javax.swing.JTextField();
        LabelValorCus114 = new javax.swing.JLabel();
        jTextNumeroPalavra = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de AOC II Primeiro Semestre de 2018");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Calculadora de AOC II  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jButtonNovo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add2.png"))); // NOI18N
        jButtonNovo.setText("Novo Calculo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonGravar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save24x24.png"))); // NOI18N
        jButtonGravar.setText("Salvar Calculo");
        jButtonGravar.setEnabled(false);
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jButtonSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel24x24.png"))); // NOI18N
        jButtonSair.setText("Cancelar");
        jButtonSair.setEnabled(false);
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonCalcular.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar24x24.png"))); // NOI18N
        jButtonCalcular.setText("Calcular");
        jButtonCalcular.setEnabled(false);
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jButtonGravar, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTextObs.setEditable(false);
        jTextObs.setColumns(1);
        jTextObs.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextObs.setLineWrap(true);
        jTextObs.setRows(1);
        jTextObs.setText("Tamanho Total da cache:\n\nCapacidade  para armazenamento de informações do usuario:\n\nLargura da palavra:\n\nTamanho do campo de deslocamento:\n\nNúmero de conjuntos da cache:\n\nTamanho do campo de índice do endereço:\n\nTamanho do campo TAG do endereço:");
        jTextObs.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextObs.setEnabled(false);
        jScrollPane4.setViewportView(jTextObs);

        jTextCapacidadeCache.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCapacidadeCache.setEnabled(false);
        jTextCapacidadeCache.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCapacidadeCache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCapacidadeCacheActionPerformed(evt);
            }
        });

        LabelValorCus112.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus112.setText("Capacidade da cache (em KB) para armazenamento de informações do usuario:");

        LabelValorCus113.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus113.setText("Largura (em bytes) da palavra:");

        jTextLarguraPalavra.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextLarguraPalavra.setEnabled(false);
        jTextLarguraPalavra.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextLarguraPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLarguraPalavraActionPerformed(evt);
            }
        });

        LabelValorCus114.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus114.setText("Número de palavras por bloco:");

        jTextNumeroPalavra.setEditable(false);
        jTextNumeroPalavra.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextNumeroPalavra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextNumeroPalavra.setText("1");
        jTextNumeroPalavra.setEnabled(false);
        jTextNumeroPalavra.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextNumeroPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumeroPalavraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelValorCus112)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCapacidadeCache, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelValorCus113, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4)
                            .addComponent(jSeparator1))
                        .addGap(5, 5, 5))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelValorCus114)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextLarguraPalavra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextNumeroPalavra, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextCapacidadeCache, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(LabelValorCus112, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelValorCus113, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jTextLarguraPalavra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelValorCus114, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNumeroPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void limpaCampo() {
        jTextObs.setText(null);
        jTextCapacidadeCache.setText("");
        jTextLarguraPalavra.setText("");
    }

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        this.limpaCampo();
        this.jTextCapacidadeCache.setEnabled(true);
        this.jTextLarguraPalavra.setEnabled(true);
        this.jButtonNovo.setEnabled(false);
        this.jButtonCalcular.setEnabled(true);
        this.jButtonSair.setEnabled(true);


    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        this.limpaCampo();
        this.jButtonGravar.setEnabled(false);
        this.jButtonNovo.setEnabled(false);

    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.limpaCampo();
        this.jTextCapacidadeCache.setEnabled(false);
        this.jTextLarguraPalavra.setEnabled(false);
        this.jButtonGravar.setEnabled(false);
        this.jButtonNovo.setEnabled(true);
        this.jButtonSair.setEnabled(false);
        this.jButtonCalcular.setEnabled(false);


    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        if (jTextCapacidadeCache.getText().equals("0") || jTextCapacidadeCache.getText().equals("") || jTextLarguraPalavra.getText().equals("0") || jTextLarguraPalavra.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Verifique os Valores de Entrada!!", "Erro ao Calcular", JOptionPane.WARNING_MESSAGE);
        } else {
            //Le dados da tela e coloca na cache
            CacheDMNew cache = new CacheDMNew(Float.parseFloat(jTextCapacidadeCache.getText()), Float.parseFloat(jTextLarguraPalavra.getText()), Float.parseFloat(jTextNumeroPalavra.getText()));
            //inicializa a cache1
            CacheDMNew cache1 = new CacheDMNew(0, 0, 1);
            //Estancia Cache_dm_tam_total
            Cache_dm_tam_total result_calc = new Cache_dm_tam_total();
            //efetua o calculo e salva na cache1
            cache1 = result_calc.Calc(cache);
            //Mostra na tela os resultados
            jTextObs.setText("Tamanho Total da cache: " + cache1.getT_total() + "\n\n" + "Capacidade  para armazenamento de informações do usuario: "
                    + cache1.getT_user() + "\n\n" + "Largura da palavra: " + cache1.getT_word() + "\n\n" + "Tamanho do campo de deslocamento: " + cache1.getOb() + "\n\n"
                    + "Número de conjuntos da cache: " + cache1.getN_conj() + "\n\n" + "Tamanho do campo de índice do endereço: " + cache1.getT_ind() + "\n\n"
                    + "Tamanho do campo TAG do endereço: " + cache1.getTag() + "\n\n " );

            this.jButtonGravar.setEnabled(true);
        }

    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jTextCapacidadeCacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCapacidadeCacheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCapacidadeCacheActionPerformed

    private void jTextLarguraPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLarguraPalavraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLarguraPalavraActionPerformed

    private void jTextNumeroPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumeroPalavraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumeroPalavraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelValorCus112;
    private javax.swing.JLabel LabelValorCus113;
    private javax.swing.JLabel LabelValorCus114;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextCapacidadeCache;
    private javax.swing.JTextField jTextLarguraPalavra;
    private javax.swing.JTextField jTextNumeroPalavra;
    private javax.swing.JTextArea jTextObs;
    // End of variables declaration//GEN-END:variables
}
